import java.util.Arrays;

class UniversityRunner
{
	public static void main(String[] args)
	{
		String[] universities={"R.V. College of Engineering","BMS College of Engineering","PES University",
		"Dayananda Sagar College of Engineering","MS Ramaiah Institute of Technology","JSS Academy of Technical Education",
		"New Horizon College of Engineering","CMR Institute of Technology","Acharya Institute of Technology",
		"Bangalore Institute of Technology","Christ University","Jain University","PES University","REVA University",
		"Presidency University","Garden City University","Alliance University","Siddaganga Institute of Technology",
		"NMAM Institute of Technology","Mangalore Institute of Technology and Engineering","KLE Technological University",
		"SDM College of Engineering and Technology","Cambridge Institute of Technology","East West Institute of Technology",
		"Global Academy of Technology","Sir M Visvesvaraya Institute of Technology","Kristu Jayanti College","Mount Carmel College",
		"St Joseph's College of Commerce","Administrative Management College","Kristu Jayanti College","MVJ College of Engineering",
		"Dr Ambedkar Institute of Technology","KNS Institute of Technology","Rajeev Institute of Technology",
		"ATME College of Engineering","GSSS Institute of Engineering and Technology for Women","Vidya Vikas Institute of Engineering and Technology",
		"Malnad College of Engineering","Canara Engineering College","Sahyadri College of Engineering and Management",
		"Yenepoya Institute of Technology","Tontadarya College of Engineering","Basaveshwar Engineering College",
		"Angadi Institute of Technology and Management","KLS Gogte Institute of Technology","Bheemanna Khandre Institute of Technology",
		"Ballari Institute of Technology and Management","Proudadevaraya Institute of Technology","Rao Bahadur Y Mahabaleswarappa Engineering College",
		"Government Engineering College","Visvesvaraya Technological University","University of Mysore","Mangalore University",
		"Karnatak University","Kuvempu University","Davangere University","Tumkur University","Rani Channamma University",
		"CMR University","Acharya Institute of Graduate Studies","Oxford College of Engineering","The National Institute of Engineering",
		"Sri Jayachamarajendra College of Engineering","Bangalore Technological Institute","Brindavan College of Engineering",
		"Don Bosco Institute of Technology","HKBK College of Engineering","Dayananda Sagar University","Nitte Meenakshi Institute of Technology",
		"Reva Institute of Technology and Management","Sri Venkateshwara College of Engineering","Alpha College of Engineering",
		"AMC Engineering College","Atria Institute of Technology","Sambhram Institute of Technology",
		"BNM Institute of Technology","APS College of Engineering","East Point College of Engineering and Technology",
		"GM Institute of Technology","Jain Institute of Technology","BIET College of Engineering","PDA College of Engineering",
		"R.V. College of Engineering","BMS College of Engineering","PES University",
		"Dayananda Sagar College of Engineering","MS Ramaiah Institute of Technology","JSS Academy of Technical Education",
		"New Horizon College of Engineering","CMR Institute of Technology","Acharya Institute of Technology",
		"Bangalore Institute of Technology","Christ University","Jain University","PES University","REVA University",
		"Presidency University","Garden City University","Alliance University","Siddaganga Institute of Technology",
		"NMAM Institute of Technology","Mangalore Institute of Technology and Engineering","KLE Technological University",
		"SDM College of Engineering and Technology","Cambridge Institute of Technology","East West Institute of Technology",
		"Global Academy of Technology","Sir M Visvesvaraya Institute of Technology","Kristu Jayanti College","Mount Carmel College",
		"St Joseph's College of Commerce","Administrative Management College","Kristu Jayanti College","MVJ College of Engineering",
		"Dr Ambedkar Institute of Technology","KNS Institute of Technology","Rajeev Institute of Technology",
		"ATME College of Engineering","GSSS Institute of Engineering and Technology for Women","Vidya Vikas Institute of Engineering and Technology",
		"Malnad College of Engineering","Canara Engineering College","Sahyadri College of Engineering and Management",
		"Yenepoya Institute of Technology","Tontadarya College of Engineering","Basaveshwar Engineering College",
		"Angadi Institute of Technology and Management","KLS Gogte Institute of Technology","Bheemanna Khandre Institute of Technology",
		"Ballari Institute of Technology and Management","Proudadevaraya Institute of Technology","Rao Bahadur Y Mahabaleswarappa Engineering College",
		"Government Engineering College","Visvesvaraya Technological University","University of Mysore","Mangalore University",
		"Karnatak University","Kuvempu University","Davangere University","Tumkur University","Rani Channamma University",
		"CMR University","Acharya Institute of Graduate Studies","Oxford College of Engineering","The National Institute of Engineering",
		"Sri Jayachamarajendra College of Engineering","Bangalore Technological Institute","Brindavan College of Engineering",
		"Don Bosco Institute of Technology","HKBK College of Engineering","Dayananda Sagar University","Nitte Meenakshi Institute of Technology",
		"Reva Institute of Technology and Management","Sri Venkateshwara College of Engineering","Alpha College of Engineering",
		"AMC Engineering College","Atria Institute of Technology","Sambhram Institute of Technology",
		"BNM Institute of Technology","APS College of Engineering","East Point College of Engineering and Technology",
		"GM Institute of Technology","Jain Institute of Technology","BIET College of Engineering","PDA College of Engineering",
		"R.V. College of Engineering","BMS College of Engineering","PES University",
		"Dayananda Sagar College of Engineering","MS Ramaiah Institute of Technology","JSS Academy of Technical Education",
		"New Horizon College of Engineering","CMR Institute of Technology","Acharya Institute of Technology",
		"Bangalore Institute of Technology","Christ University","Jain University","PES University","REVA University",
		"Presidency University","Garden City University","Alliance University","Siddaganga Institute of Technology",
		"NMAM Institute of Technology","Mangalore Institute of Technology and Engineering","KLE Technological University",
		"SDM College of Engineering and Technology","Cambridge Institute of Technology","East West Institute of Technology",
		"Global Academy of Technology","Sir M Visvesvaraya Institute of Technology","Kristu Jayanti College","Mount Carmel College",
		"St Joseph's College of Commerce","Administrative Management College","Kristu Jayanti College","MVJ College of Engineering",
		"Dr Ambedkar Institute of Technology","KNS Institute of Technology","Rajeev Institute of Technology",
		"ATME College of Engineering","GSSS Institute of Engineering and Technology for Women","Vidya Vikas Institute of Engineering and Technology",
		"Malnad College of Engineering","Canara Engineering College","Sahyadri College of Engineering and Management",
		"Yenepoya Institute of Technology","Tontadarya College of Engineering","Basaveshwar Engineering College",
		"Angadi Institute of Technology and Management","KLS Gogte Institute of Technology","Bheemanna Khandre Institute of Technology",
		"Ballari Institute of Technology and Management","Proudadevaraya Institute of Technology","Rao Bahadur Y Mahabaleswarappa Engineering College",
		"Government Engineering College","Visvesvaraya Technological University","University of Mysore","Mangalore University",
		"Karnatak University","Kuvempu University","Davangere University","Tumkur University","Rani Channamma University",
		"CMR University","Acharya Institute of Graduate Studies","Oxford College of Engineering","The National Institute of Engineering",
		"Sri Jayachamarajendra College of Engineering","Bangalore Technological Institute","Brindavan College of Engineering",
		"Don Bosco Institute of Technology","HKBK College of Engineering","Dayananda Sagar University","Nitte Meenakshi Institute of Technology",
		"Reva Institute of Technology and Management","Sri Venkateshwara College of Engineering","Alpha College of Engineering",
		"AMC Engineering College","Atria Institute of Technology","Sambhram Institute of Technology",
		"BNM Institute of Technology","APS College of Engineering","East Point College of Engineering and Technology",
		"GM Institute of Technology","Jain Institute of Technology","BIET College of Engineering","PDA College of Engineering",
		"R.V. College of Engineering","BMS College of Engineering","PES University",
		"Dayananda Sagar College of Engineering","MS Ramaiah Institute of Technology","JSS Academy of Technical Education",
		"New Horizon College of Engineering","CMR Institute of Technology","Acharya Institute of Technology",
		"Bangalore Institute of Technology","Christ University","Jain University","PES University","REVA University",
		"Presidency University","Garden City University","Alliance University","Siddaganga Institute of Technology",
		"NMAM Institute of Technology","Mangalore Institute of Technology and Engineering","KLE Technological University",
		"SDM College of Engineering and Technology","Cambridge Institute of Technology","East West Institute of Technology",
		"Global Academy of Technology","Sir M Visvesvaraya Institute of Technology","Kristu Jayanti College","Mount Carmel College",
		"St Joseph's College of Commerce","Administrative Management College","Kristu Jayanti College","MVJ College of Engineering",
		"Dr Ambedkar Institute of Technology","KNS Institute of Technology","Rajeev Institute of Technology",
		"ATME College of Engineering","GSSS Institute of Engineering and Technology for Women","Vidya Vikas Institute of Engineering and Technology",
		"Malnad College of Engineering","Canara Engineering College","Sahyadri College of Engineering and Management",
		"Yenepoya Institute of Technology","Tontadarya College of Engineering","Basaveshwar Engineering College",
		"Angadi Institute of Technology and Management","KLS Gogte Institute of Technology","Bheemanna Khandre Institute of Technology",
		"Ballari Institute of Technology and Management","Proudadevaraya Institute of Technology","Rao Bahadur Y Mahabaleswarappa Engineering College",
		"Government Engineering College","Visvesvaraya Technological University","University of Mysore","Mangalore University",
		"Karnatak University","Kuvempu University","Davangere University","Tumkur University","Rani Channamma University",
		"CMR University","Acharya Institute of Graduate Studies","Oxford College of Engineering","The National Institute of Engineering",
		"Sri Jayachamarajendra College of Engineering","Bangalore Technological Institute","Brindavan College of Engineering",
		"Don Bosco Institute of Technology","HKBK College of Engineering","Dayananda Sagar University","Nitte Meenakshi Institute of Technology",
		"Reva Institute of Technology and Management","Sri Venkateshwara College of Engineering","Alpha College of Engineering",
		"AMC Engineering College","Atria Institute of Technology","Sambhram Institute of Technology",
		"BNM Institute of Technology","APS College of Engineering","East Point College of Engineering and Technology",
		"GM Institute of Technology","Jain Institute of Technology","BIET College of Engineering","PDA College of Engineering",
		"R.V. College of Engineering","BMS College of Engineering","PES University",
		"Dayananda Sagar College of Engineering","MS Ramaiah Institute of Technology","JSS Academy of Technical Education",
		"New Horizon College of Engineering","CMR Institute of Technology","Acharya Institute of Technology",
		"Bangalore Institute of Technology","Christ University","Jain University","PES University","REVA University",
		"Presidency University","Garden City University","Alliance University","Siddaganga Institute of Technology",
		"NMAM Institute of Technology","Mangalore Institute of Technology and Engineering","KLE Technological University",
		"SDM College of Engineering and Technology","Cambridge Institute of Technology","East West Institute of Technology",
		"Global Academy of Technology","Sir M Visvesvaraya Institute of Technology","Kristu Jayanti College","Mount Carmel College",
		"St Joseph's College of Commerce","Administrative Management College","Kristu Jayanti College","MVJ College of Engineering",
		"Dr Ambedkar Institute of Technology","KNS Institute of Technology","Rajeev Institute of Technology",
		"ATME College of Engineering","GSSS Institute of Engineering and Technology for Women","Vidya Vikas Institute of Engineering and Technology",
		"Malnad College of Engineering","Canara Engineering College","Sahyadri College of Engineering and Management",
		"Yenepoya Institute of Technology","Tontadarya College of Engineering","Basaveshwar Engineering College",
		"Angadi Institute of Technology and Management","KLS Gogte Institute of Technology","Bheemanna Khandre Institute of Technology",
		"Ballari Institute of Technology and Management","Proudadevaraya Institute of Technology","Rao Bahadur Y Mahabaleswarappa Engineering College",
		"Government Engineering College","Visvesvaraya Technological University","University of Mysore","Mangalore University",
		"Karnatak University","Kuvempu University","Davangere University","Tumkur University","Rani Channamma University",
		"CMR University","Acharya Institute of Graduate Studies","Oxford College of Engineering","The National Institute of Engineering",
		"Sri Jayachamarajendra College of Engineering","Bangalore Technological Institute","Brindavan College of Engineering",
		"Vidya Vikas Institute of Engineering and Technology","Jawaharlal Nehru National College of Engineering"};
		
		System.out.println(universities.length);
		
		for(int index=0;index<universities.length;index++)
		{
			System.out.println("Courses : "+Arrays.toString(University.getCourse(universities[index])));
		}
		
		

	}
}